# Generated by Django 5.1.7 on 2025-04-16 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=13, unique=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gender')),
                ('school', models.CharField(max_length=100)),
                ('previous_club', models.CharField(max_length=100)),
                ('years_of_training', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's Name")),
                ('mother_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Mother's Phone")),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Mother's Email")),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's Name")),
                ('father_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name="Father's Phone")),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Father's Email")),
                ('amount_owed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID', 'Identification Document'), ('CONTRACT', 'Contract'), ('PICTURE', 'Player Picture')], default='OTHER', max_length=20, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='player_documents/', verbose_name='File')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='napoli_app.player', verbose_name='Player')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
