# Generated by Django 5.1.7 on 2025-04-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napoli_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age_group',
            field=models.IntegerField(default=0),
        ),
    ]
