# Generated by Django 5.2 on 2025-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napoli_app', '0002_player_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id_number',
            field=models.CharField(max_length=13),
        ),
    ]
