# Generated by Django 5.1.7 on 2025-04-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napoli_app', '0004_alter_player_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='napoli_app.player'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
