# Generated by Django 5.1.7 on 2025-04-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napoli_app', '0005_alter_document_options_alter_document_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_group',
            field=models.CharField(choices=[('U12', 'Under 12'), ('U14', 'Under 14'), ('U17', 'Under 17'), ('SENIOR', 'Senior')], default='U12', max_length=10),
        ),
    ]
